Added fade animation feature on MissionPillar, About, and Event. Text…
reactdeveloperske/reactdevske-website pull request #129
Opened 2023-03-28 12:12 UTC by Zackius

… border bottom in componenets headers

## Added Animation to MissionPillar, About, and Event Files

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-10 08:57 UTC, orama254 commented
Hello @Zackius 

Your preview build seems to be failing on our end. Are the packages resolved correctly on your end?

2023-04-11 08:25 UTC, Zackius commented
I looked at the issue, packages are resolved.

2023-04-13 16:56 UTC, orama254 reviewed
@Zackius 
The error happens on the event component as well. Check it out

PATH: /src/components/Events/Events.tsx

2023-04-13 17:05 UTC, Zackius commented
Error resolved on Event file.

On Thu, 13 Apr 2023 at 19:56, ramadevsign ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> @Zackius <https://github.com/Zackius>
> The error happens on the event component as well. Check it out
>
> PATH: /src/components/Events/Events.tsx
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/reactdeveloperske/reactdevske-website/pull/129#pullrequestreview-1383847310>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVBIWS6RVO465NDBC4I3DU3XBAV37ANCNFSM6AAAAAAWKPIQYA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-04-17 16:31 UTC, orama254 requested changes
Check out the additional comments for your review.

2023-04-17 16:31 UTC, orama254 commented on src/components/AboutUs/AboutUs.tsx
I can see an additional underline on the h2, could you have that resolved so as to maintain the original design specifications

2023-04-17 16:31 UTC, orama254 commented on src/components/ContactUs/DesktopVersion.tsx
> +  const [state, handleSubmit] = useForm("process.env.NEXT_PUBLIC_FORMSPREE_ID!");
remove the extra "" marks from the environment variable declaration.

2023-04-17 16:31 UTC, orama254 commented on src/components/ContactUs/DesktopVersion.tsx
> +            sitekey={"process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY!"}
remove the extra "" marks from the environment variable declaration.

2023-04-17 16:31 UTC, orama254 commented on src/components/Events/Events.tsx
> +      <Fade direction='right'>
Could you the fade direction to down

2023-04-17 16:31 UTC, orama254 commented on src/components/HeroHeader/DesktopHero.tsx
For the hero section, could you add the fade direction to down?

2023-04-17 16:31 UTC, orama254 commented on src/components/MissionPillars/MissionPillars.tsx
> +      <h2 className="md:uppercase border-b-2 border-slate-400  font-bold md:font-light text-2xl md:text-5xl">
Remove the additional underline on the h2 to maintain consistency with the initial design.

2023-04-24 22:32 UTC, orama254 requested changes
Nice progress @Zackius , 

also remove the underlines from the about us section heading and the events section heading.

See deployed preview for perspective [HERE](https://reactdevske-website-rehjlb39b-react-developers-kenya.vercel.app/)

2023-05-18 16:07 UTC, orama254 approved these changes
Looks Good ✅

2023-05-18 16:07 UTC, merged